# Generated by Django 2.1.5 on 2019-06-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190603_0018'),
        ('posts', '0004_auto_20190602_2228'),
    ]

    operations = [
    ]
